### ISSUE TITLE
Sauce REST downloadVideo method is not working, throwing an exception and APi url also broken in the method 

### ISSUE THREAD

**Issue by madhusudhanmulkalapally** [saucelabs/saucerest-java#238] opened 2022-05-17 08:20 UTC
When I try to download RDC vidoes by suing sauce rest method which is downloadVideo method, getting an error

**Comment by sceiler** [comment] 2022-06-20 09:10
@madhusudhanmulkalapally please use the issue templates to raise issues. Furthermore, without more information or details we cannot reproduce the issue you are reporting. I am closing this issue the above mentioned reasons.

**Closed by sceiler** 2022-06-20 09:10 UTC
