### ISSUE TITLE
Can't access to har

### ISSUE THREAD

**Issue by romainlouvet** [saucelabs/saucerest-java#80] opened 2019-07-08 11:55 UTC
since 1 week we can't access to har file

sauce.getHARDataStream(jobId);

->
java.io.FileNotFoundException: https://eu-central-1.saucelabs.com/rest/v1/lbc_france/jobs/d21a9a247f254a00927f260201a93793/assets/network.har

version 1.0.44

from saucelabs website I can access to network panel (https://eds.eu-central-1.saucelabs.com/d21a9a247f254a00927f260201a93793/network.har)

**Comment by javydreamercsw** [comment] 2020-01-08 15:01
Seems to be a duplicate of #56.

**Comment by enriquegh** [comment] 2020-02-24 19:01
Duplicate of #56

**Closed by enriquegh** 2020-02-24 19:01 UTC
